FROM python:3.5
MAINTAINER https://github.com/sthysel/docker-mathics

ENV VERSION 0.9

RUN groupadd -g __GID__ mathman
RUN useradd --uid __UID__ --gid __GID__ mathman

# install
RUN mkdir /src/ 
WORKDIR /src/

RUN curl -sL https://github.com/mathics/Mathics/archive/v${VERSION}.tar.gz | tar xz 
RUN cd ./Mathics-${VERSION} && python setup.py install

VOLUME /work
WORKDIR /work

USER mathman

